apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql.app.svc.cluster.local
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef: 
                  name: db-sql
                  key: mysql-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: db-sql
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef: 
                  name: db-sql
                  key: mysql-database
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi