apiVersion: v1
kind: Secret
metadata:
  name: db-sql
  namespace: wordpress
type: Opaque
data:
  userid: dXNlcm5hbWU= 
  # username
  userpass: cGFzc3dvcmQ=
  # password
  password: cm9vdF9wYXNzd29yZA==
  # root_password
  dbname: d29yZHByZXNzX2Ri
  # wordpress_db